### ISSUE TITLE
カレンダーIDについて

### ISSUE THREAD

**Issue by lolimaru** [okapiffxiv/xivraidteam#5]
カレンダーIDのドメインが@gmail.comで指定されているため、
個人のカレンダーへの登録になってしまうようです。

グループカレンダーIDのドメイン@group.calendar.google.comも対応できるように、
@gmai.comの指定を取り外すことは可能ですか？

**Comment by okapiffxiv** [comment]
対応しました。
よろしくおねがいします。

**Comment by lolimaru** [comment]
ありがとうございました。
